use-sort:
    sort-type: alph
    sort-direction: asc

header: |
    /**
     * AistGitTools (http://mateuszsitek.com/projects/aist-git-tools)
     *
     * @link      http://github.com/ma-si/aist-git-tools for the canonical source repository
     * @copyright Copyright (c) 2006-2017 Aist Internet Technologies (http://aist.pl) All rights reserved.
     * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause
     */
